[toolchain]
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
par_escrow = "FASTUQ11TbpbpQL1LitzgwjLcpqRPgQrHXmuk584hypF"

[provider]
cluster = "devnet"
wallet = "../keys/me.json"
