-- Buyer contact and seller mail for a title handoff.
-- The PAR server writes these with the service role. Row security stays on and there is no public policy.

create table public.handoff_mail (
  cluster text not null check (cluster in ('devnet', 'mainnet-beta')),
  wallet text not null check (char_length(wallet) between 32 and 44),
  email text not null check (char_length(email) between 6 and 120),
  updated_at timestamptz not null default now(),
  primary key (cluster, wallet)
);

create table public.handoff_reach (
  cluster text not null check (cluster in ('devnet', 'mainnet-beta')),
  title text not null check (char_length(title) between 32 and 44),
  wallet text not null check (char_length(wallet) between 32 and 44),
  body text not null check (char_length(body) between 1 and 500),
  updated_at timestamptz not null default now(),
  primary key (cluster, title, wallet)
);

create table public.handoff_hold (
  cluster text not null check (cluster in ('devnet', 'mainnet-beta')),
  title text not null check (char_length(title) between 32 and 44),
  owner text not null check (char_length(owner) between 32 and 44),
  signature text,
  held_at timestamptz,
  mail text not null default 'pending' check (mail in ('pending', 'sent', 'skip', 'wait')),
  nudge text not null default 'open' check (nudge in ('open', 'sent', 'wait', 'skip')),
  intro text not null default 'open' check (intro in ('open', 'sent')),
  primary key (cluster, title, owner)
);

create index handoff_hold_nudge_idx on public.handoff_hold (cluster, held_at) where nudge <> 'sent';

create table public.handoff_note (
  id bigint generated by default as identity primary key,
  cluster text not null check (cluster in ('devnet', 'mainnet-beta')),
  title text not null check (char_length(title) between 32 and 44),
  wallet text not null check (char_length(wallet) between 32 and 44),
  body text not null check (char_length(body) between 1 and 500),
  signature text not null check (char_length(signature) between 64 and 200),
  mail text not null default 'pending' check (mail in ('pending', 'sent', 'wait', 'skip')),
  created_at timestamptz not null default now(),
  unique (cluster, signature)
);

create index handoff_note_title_idx on public.handoff_note (cluster, title, created_at);

create table public.helius_hooks (
  cluster text not null check (cluster in ('devnet', 'mainnet-beta')),
  hook_id text not null,
  updated_at timestamptz not null default now(),
  primary key (cluster)
);

alter table public.handoff_mail enable row level security;
alter table public.handoff_reach enable row level security;
alter table public.handoff_hold enable row level security;
alter table public.handoff_note enable row level security;
alter table public.helius_hooks enable row level security;
