-- One row for every handoff letter the platform tries to send.
-- The PAR server writes these with the service role. Row security stays on and there is no public policy.

create table public.handoff_letter (
  id bigint generated by default as identity primary key,
  cluster text not null check (cluster in ('devnet', 'mainnet-beta')),
  title text not null check (char_length(title) between 32 and 44),
  kind text not null check (char_length(kind) between 1 and 40),
  side text not null check (side in ('sale', 'purchase')),
  subject text not null check (char_length(subject) between 1 and 200),
  body text not null check (char_length(body) between 1 and 4000),
  status text not null check (status in ('sent', 'idle', 'retry')),
  note text not null default '' check (char_length(note) <= 200),
  created_at timestamptz not null default now()
);

create index handoff_letter_title_idx on public.handoff_letter (cluster, title, created_at);

alter table public.handoff_letter enable row level security;
